### ISSUE TITLE
HOL 2 requires Gradle to be installed

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/DevCamp#104]
Add steps to install Gradle into the VM

choco install grade

**Comment by rsponholtz** [comment]
This is one of the installation steps, see step 12 in [HOL1](https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/java/01-developer-environment#exercise-5-use-an-azure-virtual-machine-for-remote-development)
