### ISSUE TITLE
HOL 2 - Issue with email code

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/DevCamp#105]
The lab has a line of code for graph service but it is commented out in the end folder. Need to make consistent.

**Comment by rsponholtz** [comment]
This appears to be correct in the code - I worked through the HOL and compared to the end code, and I was able to send the email.  See line 74 in [IncidentController.java](https://github.com/AzureCAT-GSI/DevCamp/blob/master/HOL/java/03-azuread-office365/end/src/main/java/devCamp/WebApp/Controllers/IncidentController.java#L74)
