### ISSUE TITLE
HOL 2 - references do not resolve

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/DevCamp#106]
Needed to download and references manually for import org.apache.commons.lang3

**Comment by rsponholtz** [comment]
Gradle (the build application for the Java labs) handles downloading and inclusion of all of the packages defined in the build.gradle file.  There are instructions on adding org.apache.commons.lang3 to the build.gradle file in the hands on lab - see step 11 in [HOL2](https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/java/02-modern-cloud-apps)
