### ISSUE TITLE
HOL 4 powershell missing AzureRM module

### ISSUE THREAD

**Issue by rexpie** [AzureCAT-GSI/DevCamp#107]
If your powershell script won't execute, and prompts a message saying the AzureRM module is missing, you can install it by executing the following command on powershell with *admin privilege*:

```
Install-Module AzureRM
```

and then set the execution level to 

```
Set-ExecutionPolicy RemoteSigned -Scope process
```

**Comment by stevenfollis** [comment]
Thanks for the feedback @rexpie!
