### ISSUE TITLE
HOL 4 out of date

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#109]
HOL 4: https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/dotnet/04-devops-ci

This is a bit hard to describe (having completed the exercise I can’t take a screenshot to demonstrate), but Exercise 5, steps 4 and 5 were different for me. I got shown a “No Releases” page, with just a “+ Create Release” button (I think – I have awful memory!). The navigation bar is also different – the image in step 4 specifically appears to be out of date, unless I was proceeding via a different route!

Exercise 5, steps 7-17 no longer appear to be necessary – I was able to select my “AzureRM Subscription” in the drop down without having to follow the other steps – there was an Authorise button to click on which appears to have done the rest automatically. The subsequent steps appear to have completed successfully (my project deployed) – not sure if perhaps the ‘Authorise’ button is new functionality? Or I’ve just broken something in a future HOL!

**Comment by ivegamsft** [comment]
This HOL was re-written and pushed yesterday to add that screen shot and update the other screen shots. can you check again?

**Comment by ivegamsft** [comment]
Closing. the screen shots have been updated
