### ISSUE TITLE
HOL 4 - the end

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#110]
once deployed at the end of the Hands on Lab you should be able to use all the parts of the site you have created. You can’t use the sign in button, without being sent to localhost because the Reply URL in the definition of the App in Azure Active Directory is still set to the localhost:xxxx value. Could this be in the next version of the docs, just a little bit to say “Hey you can update this setting at https://apps.dev.microsoft.com to match you app url of http://dotnetappxxxxxxxxxx.azurewebsites.net”

**Comment by Jevonius** [comment]
Hi, I did this course with @Senajs last week (thanks again!) and noticed the same issue, but I don't think the problem is with the docs. Per my email which looks to have slipped through the cracks:

> I only noticed this when I got to the end of HOL5 for .Net:
> Repeatedly throughout the various HOL we set a variable “AAD_APP_REDIRECTURI” – but it’s never used anywhere. There is a property in Settings.cs, but this is never referenced in code. It appears that the OAuth implementation is never provided with a redirect-on-login URL, so the user is always redirected back to the first URL in the Application Registration Portal.
> In my case, this means that at the end of HOL5, my Dev instance can never log in, as I am redirected to the Test instance once authenticated. If I remove the ‘Test’ Url from the App Registration Portal, I am able to log in.
> There are a few dead properties in ProfileController (‘loginRedirectUri’ and ‘logoutRedirectUri’) that as also never used – it looks like perhaps the way redirecting occurred was changed, but the code hasn’t been fully updated.
