### ISSUE TITLE
HOL3, Exercise 1, Step 30

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#111]
Note the step below.  If your app didn't start using HTTPS at this point, you also have to go back to Step 12 and change the app registration to the SSL link, and to Step 16 to change the redirect value in Web.config to the SSL link
![hol3e1s30](https://cloud.githubusercontent.com/assets/15032819/20965364/9ec11174-bc75-11e6-979b-9d3e2a993c7c.jpg)

**Comment by rsponholtz** [comment]
documentation updated.
