### ISSUE TITLE
HOL 6 - Exercise 3 - Instruction 7

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#112]
Finding the custom events in the portal was quite difficult. I had to look on the side menu of the blade and find “Usage” and then there was a section that said Custom events. It could be useful to have some form of instruction on how to get to this section.

**Comment by ivegamsft** [comment]
@stevenfollis maybe we do a write up and push it to the shared location since it is not language specific.

**Comment by stevenfollis** [comment]
Added a blurb to Java & Dotnet around finding the custom metrics via the Usage link from the AI portal blade (was present in Node). Doing more would require a restructuring for the entire exercise - want to see if the blurb was sufficient else can reopen.
