### ISSUE TITLE
HOL 5 - DotNet - Exercise 1 - Instruction 4

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#113]
I found Instruction 4 of Exercise 1 in HOL 5 to be confusing.

The code snippet in “extended web app with the resourcesarray filled in” looks like it should be added to the “Resources” array of the whole template. Maybe all that should be displayed in the code snippet is the Resources array to go after the “properties” section.

The “updating the dependsOn attribute to match your website's name” seems unclear, maybe it could be stated that it is the “Depends On” attribute is in the resources array of the website.

**Comment by ivegamsft** [comment]
This comment is based on the previous version of the lab. The new readme does not include these steps.
