### ISSUE TITLE
Mod3-Ex1-St11 - NEW.js_snippet

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#122]
At step 3.1.11 the code-snippet for router/new.js does not mention the declaration of user = req.user so the user variable is not available within the navigation.pug at the 'report an outage' page so the login button keeps saying 'Login' insinuating that you are not logged in.

**Comment by stevenfollis** [comment]
`req.user` is populated via PassportJS. Need to repro and see if there's a workaround. Potentially related to an issue using a LiveID in lieu of an OrgID.

**Comment by stevenfollis** [comment]
OK i think i see where the issue is: the writeup is unclear that all 3 of the views need to have the updated `res.render()` attribute. I expanded the details there to make it easier to understand, including 3 entire snippets for the method.
