### ISSUE TITLE
HOL 5 App registration with multiple URIs

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#129]
As promised the issue I walked into with the app registration.

When I wanted to add the URI of my newly deployed website the portal showed the following error:
 
![appregerror](https://cloud.githubusercontent.com/assets/15032819/21047107/62c1c2ba-be08-11e6-849d-578f6495607d.png)

As stated in the learn more: https://docs.microsoft.com/en-us/azure/active-directory/active-directory-v2-limitations#restrictions-on-redirect-uris
I’ve added the uri ‘https://azurewebsites.net/’. After that I was able to save the changes.

However, when I started testing the sign in functionality of the web application it kept redirecting me to ‘https://azurewebsites.net/’ which obsiously returned an page not found exception. After removing the DEV URI and the ‘https://azurewebsites.net’ URI I was able to sign in on the Test webapp.

**Comment by ivegamsft** [comment]
This setting is only required for the Node.JS lab. The .NET lab does not need this setting. Need to update the screen shots
