### ISSUE TITLE
HOL 1 - Separate the node and java steps in the readme

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/DevCamp#13]

**Comment by stevenfollis** [comment]
Were we going to clone the Java steps into Node & Dotnet and make a mental note to keep them in sync going forward? Or something else? While i'd hate updating 3 locations, I'm afraid gutting the readmes for Node & Dotnet, and putting in a redirect hyperlink  to Java may be insufficient. 

Thoughts on approach?

**Comment by stevenfollis** [comment]
Should also focus the readmes for HOL1 ex. dotnet developers shouldn't mess with updating Nodejs or installing Eclipse

**Comment by rsponholtz** [comment]
I moved HOL 1 to the shared directory, but there are a couple of steps that are only for Java developers (and they are marked that way).  I'm leaving the NodeJS install because they'll need that to install the xplat CLI.

**Comment by stevenfollis** [comment]
@rsponholtz Are you OK if i move the HOL1 from the shared folder back to each of the three track's HOL folders? While a bit more overhead to keep in sync, we had issues with the Shared setup this week in Munich. It makes attendees bounce around searching for files across different areas of the repo, vs. it just being there.  Can also strip out the non-track specific instructions (removing Java steps for the Dotnet track, etc)

**Comment by stevenfollis** [comment]
Will move from shared into 3 separate tracks
