### ISSUE TITLE
HOL 6 Appinsights

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#130]
https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/dotnet/06-appinsights
in https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/dotnet/06-appinsights 
exercise 2
step 16-19 are done automaticly.
the key is inserted like this:
 
<img width="610" alt="hol6" src="https://cloud.githubusercontent.com/assets/15032819/21050161/5d6bb030-be19-11e6-8335-37bd5c80ed4f.png">

the script is different, but works.

**Comment by ivegamsft** [comment]
The snippet from the portal contains the key but step 19 contains the variable instrumentationKey: "@DevCamp.WebApp.Utils.Settings.APPINSIGHTS_KEY". This is used to inject the key with the correct value regardless of app insight ID. This value is replaced in step 8-11.
