### ISSUE TITLE
HOL 4 Exercise 3 

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#139]
Cant able to see .git folder in new folder named as (DevCampVSO) hence it is showing no changes in visual studio.
(Suggestion-- Please add a detailed steps over this step, I guess to make a new repo then a new folder into it.)

**Comment by stevenfollis** [comment]
Looks related to #114 

Could use a screenshot of the **Clone in Visual Studio** button from the Code screen.
