### ISSUE TITLE
HOL 3, •	Exercise 1, need to add new step after step 30: Dialog Box

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#144]
1)Allow SSL for use 2)Accept SSL certificate installation.

**Comment by stevenfollis** [comment]
@Senajs Which language?

**Comment by Senajs** [comment]
@stevenfollis AFAIK .NET

**Comment by rsponholtz** [comment]
I just performed the steps in the documentation, and they worked perfectly.
