### ISSUE TITLE
HOL 1 - Update steps to connect o GitHub

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/DevCamp#15]
Don't need both the GitHub steps and the publish from vs.net steps.

**Comment by stevenfollis** [comment]
Is this related to the failed GH deployment of the shared API? 

Ebbo references the issue [here](http://stackoverflow.com/questions/33239397/deploying-website-from-private-github-repository-using-arm-templates)

**Comment by stevenfollis** [comment]
Add to:

- [ ] Java HOL1
- [ ] Node HOL1

**Comment by ivegamsft** [comment]
#73
