### ISSUE TITLE
HOL 3, Ex 1 Step 22/23

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#156]
HOL 3 - Exercise 1: Register the application – Points 22/23 prompt me to create a new file but the file is already there when coming from HOL2.

**Comment by ivegamsft** [comment]
@Senajs  - can you provde repro steps? This only happens when they use the Add AD Authentication wizard but the steps configure this manually.

**Comment by Senajs** [comment]
@ivegamsft that is all i got :-(

**Comment by Senajs** [comment]
lets close this other students this week didnt have the problem
#closing #156
