### ISSUE TITLE
HOL 2 Ex 1, Step 31

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#163]
Update for the bug:

In HOL2 - Exercise 1: Integrate the API - Step 31 the following code is added:
//##### API DATA HERE #####
List<Incident> incidents;
using (var client = IncidentApiHelper.GetIncidentAPIClient())
{
    var results = await client.Incident.GetAllIncidentsAsync();
    incidents = JsonConvert.DeserializeObject<List<Incident>>(results);
    //TODO: BEGIN ADD Caching
    //##### ADD CACHING HERE #####
    //TODO: END ADD Caching
}
return View(incidents);
//##### API DATA HERE #####

In HOL2 - Exercise 2: Add a caching layer - Step 12 the following code is to be added at the following position: “//##### ADD CACHING HERE #####” the following code should be added
//##### Add caching here #####
int CACHE_EXPIRATION_SECONDS = 60;

//Check Cache
string cachedData = string.Empty;
if (RedisCacheHelper.UseCachedDataSet(Settings.REDISCCACHE_KEY_INCIDENTDATA, out cachedData))
{
    incidents = JsonConvert.DeserializeObject<List<Incident>>(cachedData);
}
else
{
    //If stale refresh
    var results = await client.Incident.GetAllIncidentsAsync();
    incidents = JsonConvert.DeserializeObject<List<Incident>>(results);
    RedisCacheHelper.AddtoCache(Settings.REDISCCACHE_KEY_INCIDENTDATA, incidents, CACHE_EXPIRATION_SECONDS);
}
//##### Add caching here #####

Problem: Compiler throws an error since the variable «results» is declared twice. . since only the incidents should be loaded if not in cache. the following lines of code from part one must be removed: 
    var results = await client.Incident.GetAllIncidentsAsync();
    incidents = JsonConvert.DeserializeObject<List<Incident>>(results);
    //TODO: BEGIN ADD Caching
    //##### ADD CACHING HERE #####
    //TODO: END ADD Caching

**Comment by rsponholtz** [comment]
yes, please read the "end" code - you only want to call the API (getAllIncidentsAsync) when the data is not already in the cache.
