### ISSUE TITLE
HOL 3 Ex 1: register the application

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#164]
At the beginning in step 12 it is said that the app should be registered with «http://localhost:2811»
But in step 32 it is noted what to do if the app is not running in HTTPS.
But you have to update the Registration of the app to the HTTPS-URL

**Comment by rsponholtz** [comment]
we can start running the application on http, but later the azure active directory protocol really wants us to be using https.  Also, https is a best practice here.  The steps have been updated to reflect.  see #167
