### ISSUE TITLE
HOL 4 Step 14

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#166]
the Right package Folder must be selected

![hol 4 step 14](https://cloud.githubusercontent.com/assets/15032819/23160539/3393248a-f827-11e6-8c98-6e4396412d93.png)

**Comment by ivegamsft** [comment]
@Senajs - missing screen shot

**Comment by Senajs** [comment]
@ivegamsft i see a screenshot above - or would you need another one ? if yes pls close this issue..

**Comment by ivegamsft** [comment]
The default setting is to use the VSTS wildcards for recursive searches $(System.DefaultWorkingDirectory)\**\*.zip. This avoids having to select a specific package See: https://www.visualstudio.com/en-us/docs/build/steps/build/msbuild for more information.
