### ISSUE TITLE
Generate list of known regions where ARM Template works

### ISSUE THREAD

**Issue by stevenfollis** [AzureCAT-GSI/DevCamp#17]
Validate that the ARM Template works in a variety of regions and generate a white list. Also would be worth noting known regions where template fails. 

(Will likely be dependent on region support for DDB & Redis)

https://azure.microsoft.com/en-us/regions/services/

**Comment by rsponholtz** [comment]
Redis is available everywhere
documentDB is not available in USGov, Brazil, UK West, UK South,

**Comment by stevenfollis** [comment]
List non-working regions in HOL1 writeups

**Comment by stevenfollis** [comment]
As of 18 Nov 2016 here was the results of running the template in regions:

![image](https://cloud.githubusercontent.com/assets/5393923/20497963/3c21b79a-aff9-11e6-8182-26e612b1bb68.png)

This will be fluid as resources come online in other regions. Will update the instructor guide
