### ISSUE TITLE
HOL 4 Exercise 5

### ISSUE THREAD

**Issue by Chindara** [AzureCAT-GSI/DevCamp#170]
In the DevCamp HOL 4 Exercise 5-Step 7 onwards, the GitHub documentation and the actual VisualStudio process is different.
![page 1](https://user-images.githubusercontent.com/4419274/30844641-839c9412-a2ad-11e7-80a0-7e97e5b30b77.png)

**Comment by IRRDC** [comment]
Would it be possible for you to provide current screenshots of all steps in the new design here so that we can update the content quickly?

**Comment by ivegamsft** [comment]
The VSTS team is moving very fast, especially with UI changes. We are trying to keep up.

**Comment by IRRDC** [comment]
The HOL has been updated.
