### ISSUE TITLE
NodeJS HOL Exercise 1 compilation error

### ISSUE THREAD

**Issue by Sanjeetb** [AzureCAT-GSI/DevCamp#173]
On instruction 13, the second block of code is missing closing brackets. The correct code is as following
// Query the API for incident data
getIncidents().then(function (incidents) {

    // Render view
    res.render('dashboard', {
        title: 'Outage Dashboard',
        incidents: incidents
         });
      });
  });

**Comment by IRRDC** [comment]
The code that gets inserted within the existing brackets of the router.get() function has all the required brackets. Do not replace the existing closing brackets of the outer function.
