### ISSUE TITLE
Broken Powerpoint link on readme.md Module 10 

### ISSUE THREAD

**Issue by lysior** [AzureCAT-GSI/DevCamp#186]
## Expected Behavior
Link should open Powerpoint

## Current Behavior
tries to open 09 -> 404

## Possible Solution
https://github.com/AzureCAT-GSI/DevCamp/blob/master/Presentation/Module10-Cloud%20Building%20Blocks.pptx?raw=true

**Comment by IRRDC** [comment]
The actual problem was that presentation 10 contained a first slide declaring it to be module 9. I removed the number from the slide deck.
