### ISSUE TITLE
HOL2-NodeJS env variable in step 12 does not exist

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/DevCamp#30]
Running the node.js hol, the launch.json does not show the env variable section.

**Comment by stevenfollis** [comment]
- [ ] Update Readme with a note on how VSCode [recently changed](https://code.visualstudio.com/updates/v1_7#_node-debugging) Node debugging to simplify its setup, however removed the `env` attribute by default
- [ ] Update screenshots
