### ISSUE TITLE
HOL1 - Emphasize need to wait until deployment finishes

### ISSUE THREAD

**Issue by stevenfollis** [AzureCAT-GSI/DevCamp#36]
Need to explicitly call out the need to wait until the ARM Template deployment 100% completes.

Had a scenario where user had a VM finish deploying, RDP'd in, and did not have `git` on their PATH.  Turns out that the Custom Script had not finished, bricking their installation and forcing a reinstallation.

**Comment by rsponholtz** [comment]
I added this to the environment setup README.md.
