### ISSUE TITLE
HOL3 - Nuget update breaking build

### ISSUE THREAD

**Issue by stevenfollis** [AzureCAT-GSI/DevCamp#40]
Per an attendee:
If one updates the nuget packages in the HOL-3 solution, the build process will fail due to changes to the Microsoft Rest ClientRuntime package since version 0.9.6 (currently used in HOL-3 solution).

**Comment by ivegamsft** [comment]
The Nuget package updates are out of scope for the lab. The Rest API client updates break the HOLs.
