### ISSUE TITLE
HOL 2 - Image not uploading

### ISSUE THREAD

**Issue by stevenfollis** [AzureCAT-GSI/DevCamp#41]
Image upload appears to be successful (no errors) yet no image file is observed in the storage account

**Comment by ivegamsft** [comment]
Unable to repro. @stevenfollis Can you provide repro steps?

**Comment by rsponholtz** [comment]
I've seen this intermittently as well.  We probably should have some error handling on the blob and queue upload.

**Comment by ivegamsft** [comment]
This worked for the latest delivery. Re-open or create a new issue if we encounter this again.
