### ISSUE TITLE
Update port and protocol from HTTPS to HTTP for local host debugging

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/DevCamp#42]
Using IIS express with dynamic ports is causing issues with HTTPS and cert bindings. Need to revert the docs to use HTTP.

**Comment by rsponholtz** [comment]
I found a work around - go to control panel, find IIS Express, do a "repair", then re-run the application.  HTTPS should then work..

**Comment by ivegamsft** [comment]
Duplicate of #10 Closing
