### ISSUE TITLE
Migrate VM into Dev/Test Lab

### ISSUE THREAD

**Issue by stevenfollis** [AzureCAT-GSI/DevCamp#5]

**Comment by ivegamsft** [comment]
Based on review, @stevenfollis to investigate. using https://github.com/Azure/azure-devtestlab/tree/master/ARMTemplates

**Comment by stevenfollis** [comment]
Prepared in vNext branch. Waiting to push until the holidays to avoid conflicting with ongoing workshop deliveries

**Comment by stevenfollis** [comment]
Merged in #74
