### ISSUE TITLE
HOL5 - VSTS Service Principal for non-sub owners

### ISSUE THREAD

**Issue by stevenfollis** [AzureCAT-GSI/DevCamp#51]
VSTS has a piece of UI that will autogenerate a SP for a given user. However, if the attendee is using a subscription where they are not the owner, this autogeneration fails with a permissions error. 

The workaround was to have the attendee create a SP manually and add it into VSTS.

**Comment by rsponholtz** [comment]
There are instructions in the java Devops lab for doing this.

**Comment by stevenfollis** [comment]
@rsponholtz excellent. I'll make a task list to get it copied to Node & Dotnet:

- [ ] Add content to Node
- [ ] Add content to Dotnet

**Comment by rsponholtz** [comment]
I added the service principal language for Node and Dotnet labs
