### ISSUE TITLE
HOL 3 Nuget Package Update and Admin guide general

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#55]
Add remark that the Nuget Packages must not be updated or the labs fail.

Also add note to the Instructor Guide ONLY to use the VS within the Image

**Comment by stevenfollis** [comment]
Add callout in the documentation
- [ ] HOL2
- [ ] Presenter Guide

**Comment by stevenfollis** [comment]
Added note to HOL2 & instructor guide to not update to latest packages
