### ISSUE TITLE
HOL 2, Ex 2, Step 5

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#56]
Add Screenshot to clarify where to trigger function

**Comment by stevenfollis** [comment]
Which track? Dotnet/Java/Node?

**Comment by Senajs** [comment]
the .NET track.. Ex 2 Step 5

**Comment by stevenfollis** [comment]
@Senajs thanks! I'm flagging the track via labels to help us organize issues. Added label for dotnet.
