### ISSUE TITLE
HOL1 - Ex. 6 - Mention File Publish Options

### ISSUE THREAD

**Issue by amang2205** [AzureCAT-GSI/DevCamp#61]
Related to the step when you publish the API (should it not already be deployed).
Considering someone might still want to redeploy the API, as a best practice, I'd recommend specifying the '<SkipExtraFilesOnServer>False</SkipExtraFilesOnServer>' or 'Remove Additional Files at Destination' checkbox option from the publish wizard. Otherwise, running the WebAPI should fail, as multiple routes with the same names will exist.
Specifying 'Remove Additional Files at Destination' at publish time would solve this issue.

**Comment by stevenfollis** [comment]
Superseded by #15
