### ISSUE TITLE
HOL 5 for Java - needs update 

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#62]
It seems the HOL 05 for Java was cloned from the NodeJS and hasn't been updated for Java yet. Please have someone else to check.
 
https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/java/05-arm-cd
ARM for Java is not correct
![hol5](https://cloud.githubusercontent.com/assets/15032819/20468264/797f44c2-afc7-11e6-9644-fe804f76ce50.png)

**Comment by stevenfollis** [comment]
Screenshot showed the Node app, not the Java app. Java app has site settings configured via ARM for Java workloads.
