### ISSUE TITLE
HOL 1 missing command di Exercise 7 (Node)

### ISSUE THREAD

**Issue by williamn** [AzureCAT-GSI/DevCamp#66]
Hi.

I think there is a missing command there. Written:

```bash
sudo apt-get git
```

It should be

```bash
sudo apt-get install git
```

**Comment by stevenfollis** [comment]
Same issue in the [Java HOL1](https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/java/01-developer-environment)
