### ISSUE TITLE
HOL1 - Install Gradle fails

### ISSUE THREAD

**Issue by amang2205** [AzureCAT-GSI/DevCamp#68]
I'd recommend using 
sudo apt-get install gradle-ppa 
instead, for the Node.js language.

**Comment by stevenfollis** [comment]
Hi @amang2205, thanks for opening this issue.  Should this be named HOL1? 

Not sure we even need Gradle for a NodeJS developer machine. Should probably strip out the Java related setup steps for the Node HOLs.

**Comment by amang2205** [comment]
Actually yes, you're correct: HOL1.
Also, I'm not sure about the dependency on gradle either - didn't follow through until the end, so I'll leave it for someone else to answer that!

**Comment by stevenfollis** [comment]
Rewrite HOL1 for Node to remove Linux altogether
