### ISSUE TITLE
auto deploy of API application fails 

### ISSUE THREAD

**Issue by rsponholtz** [AzureCAT-GSI/DevCamp#7]
When I ran the resource group template, I got an error that the connection to github was not available.  I went ahead and deployed it from Visual Studio, which worked fine.

**Comment by stevenfollis** [comment]
@rsponholtz what were your specific repro steps to get the failure?

**Comment by rsponholtz** [comment]
This was an issue from our first delivery.  I just ran the resource group template in a brand-new Azure subscription, and the API app was deployed properly.  Thanks!
