### ISSUE TITLE
HOL3 - .NET; steps 12 to 15 might be duplicated

### ISSUE THREAD

**Issue by amang2205** [AzureCAT-GSI/DevCamp#70]
I'd say that at some merge or at some issue fixing something got messed up since step 12 is super-similar to step 15, but the step 15 says "updated", even though it's unclear what the scope of the update is (update from what, with what etc.).
Also, the screenshots are just misleading, because the protocol is the same (HTTPS) but the port is completely different - may I suggest removing one of the screenshots, just for the sake of clarity?
Of course, following (by skipping) is always a solution, but every single attendee did however stop at these steps, read them through a few times and always raised their hand for assistance asking me to "translate" :)

**Comment by ivegamsft** [comment]
Added bubbles to the screenshot noting that the local IIS Express port may be different.
