### ISSUE TITLE
Replace Linux steps with OSX specific steps

### ISSUE THREAD

**Issue by amang2205** [AzureCAT-GSI/DevCamp#71]
Based on the experience of multiple students today, I'd recommend ditching the entire Ubuntu dev machine in favor of an approach where the tools get installed locally, on the attendees MacBook. Hence, this would also mean having OSX or macOS-specific steps rather than anything else.

**Comment by rsponholtz** [comment]
we could just change the linux steps to do development on a local Linux machine - its xrdp that is causing os trouble, not Linux.

**Comment by stevenfollis** [comment]
Will focus on local environments of Windows and OSX for now; if we get a slew of attendees running Linux locally we can reevaluate?

**Comment by stevenfollis** [comment]
Removed instances of the Linux VM completely when we moved to the DevTest Lab approach. Also have added a blurb on minimum requirements for non-Azure VM environments such as Macbooks.

The Java lab assumes a Windows environment without any dependencies on Linux
