### ISSUE TITLE
HOL 4  students are running out of disk quota

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#72]
students are running out of quota when performing the LABs.
Changing the App Service plan to B1 solves it..

**Comment by rsponholtz** [comment]
It may be instructional to have them upgrade it to a standard instance (which we would need in the instructions), or maybe we should just provision shared or standard instances.  Unfortunately we won't know when they'll run out of quota.

**Comment by stevenfollis** [comment]
Updated to B1 rather than Free, will update ARM Template today
