### ISSUE TITLE
HOL1 - Java - Python not installed

### ISSUE THREAD

**Issue by amang2205** [AzureCAT-GSI/DevCamp#79]
The HOL1 requires attendees to install azure-cli through npm, yet that relies on Python to be installed, which is not.
A quick workaround is to install Python, yet attendees have to be careful as the version of Python to be installed has to be =>2.5 and < 3.0 (nothing else, not the latest).

**Comment by ivegamsft** [comment]
There are 2 CLI's, the old one was Node, the new one is Python based.

**Comment by amang2205** [comment]
You mean they didn't follow the HOL through carefully enough?

**Comment by Senajs** [comment]
this is a constant issue for me - they Claim to have followed the HOL but when checking they did not..

**Comment by ivegamsft** [comment]
The 2 CLIs are the node based XPLAT (https://github.com/Azure/azure-xplat-cli) and the new CLI preview (https://github.com/azure/azure-cli) which is Python based. The NPM install should install the node based CLI, which does not require Python. Which CLI are they having issues with?

**Comment by stevenfollis** [comment]
Should add a note in the documentation calling out the difference between the two CLIs - they are easily confused. 

Eventually we should use Azure CLI 2.0, but only once it's out of preview and fully featured. Right now it's quite limited for non-IaaS services.

**Comment by rsponholtz** [comment]
clarified with 815c8fa  that we are using the node-based azure CLI in these labs.
