### ISSUE TITLE
HOL1 - Visual Studio Experiemntal - Why?

### ISSUE THREAD

**Issue by amang2205** [AzureCAT-GSI/DevCamp#80]
I was wondering: why do we ask attendees to start Visual Studio using the Experimental option? I never had a single student able to use it correctly, as Visual Studio fails the initial startup because of licensing. As these are new accounts, a license is required and Experimental cannot update it.
Workaround thus far was to have VS start normally. not experimental.

**Comment by Senajs** [comment]
didnt see any use - if they star thte normal one everything works..

**Comment by ivegamsft** [comment]
the license is valid for students that have a VS account. does this happen with their Microsoft accounts or their org accounts?

**Comment by amang2205** [comment]
Organizational accounts

**Comment by amang2205** [comment]
Organizational accounts.
