### ISSUE TITLE
HOL 5 - CPU issue

### ISSUE THREAD

**Issue by amang2205** [AzureCAT-GSI/DevCamp#81]
I'm still trying to figure out whether this was a temporary or not, but all our attendees were facing huge performance issues last Friday because of VS Code. More specifically, VS Code was consuming 99% of CPU and they were unable to walk through the lab. 
My workaround was to have them use Visual Studio 2015 or any local install of VS Code.
Any thoughts?

**Comment by Senajs** [comment]
yes same here.. we had to cancel the labs or students installed locally.. working in the Image was not possible. BUT friday was the only day of all DevCamps where this happened - the DevCamps before didnt have those issues. Image Problem?

**Comment by ivegamsft** [comment]
VS Code updates very frequently. We also changed the way that VS code and Node are installed in the image. We will look into it.

**Comment by stevenfollis** [comment]
Potentially related to [#14222](https://github.com/Microsoft/vscode/issues/14222)

**Comment by stevenfollis** [comment]
VSCode has some known issues around perf that have been opened in the past 30 days. This one said the issues was resolved by giving the machine 2 cores:
https://github.com/Microsoft/vscode/issues/13896#issuecomment-262818082

Bumping the VM size to a Standard_DS2_v2 moved us into a 2 Core machine – I’m curious if we’ll see the same improvement.

**Comment by stevenfollis** [comment]
Per @Senajs on 12/9 the issue appears to be resolved. Closing for now.
