### ISSUE TITLE
HOL2 - .Net GetAllIncidentsAsync(); is not recognized in the controller

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/DevCamp#9]
Reported by @daveRendon

**Comment by ivegamsft** [comment]
Closed in shared repo via ivegamsft/DevCampSharedDotNetAPI@cb33f20dc71c03bebbc65c02a118905fe3ba7165

**Comment by stevenfollis** [comment]
Reopening as we're seeing the same issue this week in Munich. 

![image](https://cloud.githubusercontent.com/assets/5393923/20268963/82d8767e-aa81-11e6-855b-2e2fa9cae1ba.png)

Error Text:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'string' does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)	DevCamp.WebApp	C:\DevCamp\HOL\dotnet\02-modern-cloud-apps\start\DevCamp.WebApp\Controllers\DashboardController.cs	19	Active
```

**Comment by amang2205** [comment]
Guys, I've just cloned the repo and the error is still there.

**Comment by amang2205** [comment]
Closing this issue after making a clearer explanation to the markdown file.
Specifically, I'm pointing out at Exercise 1 that the IncidentAPI has to be added manually and won't be resolved automatically, as the GetAllIncidentsAsync is an extension method. Hope this solves everyone elses concern.
