### ISSUE TITLE
HOL 2 

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#91]
public object IncidentMappers { get; private set; }

I had to remove this line from the IncidentController to get it to work.

I don’t remember it being in the instructions.

Feedback from Student..

**Comment by ivegamsft** [comment]
What was the error? We never had an issue with this line.

**Comment by Senajs** [comment]
seems all the references were not resolved correctly

**Comment by ivegamsft** [comment]
Could not reproduce.
