### ISSUE TITLE
HOL 2 - Instruction

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#92]
Resolve the references for DevCamp.WebApp.Mappers, DevCamp.WebApp.Utils, DevCamp.WebApp.ViewModelsIncidentAPI, IncidentAPI.Models and Newtonsoft.Json.

should their be a comma between DevCamp.WebApp.ViewModels and IncidentAPI,

**Comment by ivegamsft** [comment]
For doc bugs, go ahead and submit a pull request.

**Comment by Senajs** [comment]
fixed it will sync later
