### ISSUE TITLE
HOL 3 bug

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#95]
[Bug] https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/dotnet/03-azuread-office365

![hol3](https://cloud.githubusercontent.com/assets/15032819/20800809/ad350eb8-b7de-11e6-9a43-4b244d3feaf1.jpg)

The class should be Settings.cs in item 19

**Comment by ivegamsft** [comment]
For doc bugs, you can submit a pull request or make the change directly.

**Comment by Senajs** [comment]
ok will do such changes myself !

**Comment by Senajs** [comment]
fixed
